Servientrega/Models/AvionViewModel.cs
using Servientrega.Data.Models;
using System;
using System.Collections.Generic;

namespace Servientrega.Models
{
    public class AvionViewModel
    {
        public Guid Id { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime UpdateTime { get; set; }
        public string Modelo { get; set; }
        public int Capacidad { get; set; }
        public string Descripcion { get; set; }
        public List<Avion> ListAvion { get; set; }
    }
}

Servientrega/Models/ErrorViewModel.cs
using System;

namespace Servientrega.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Servientrega/Models/Profile/ServientregaUIProfile.cs
using AutoMapper;
using Servientrega.Data.Models;

namespace Servientrega.Models
{
    public class ServientregaUIProfile : Profile
    {
        public ServientregaUIProfile()
        {
            CreateMap<Avion, AvionViewModel>();
            CreateMap<AvionViewModel, Avion>();
        }
    }
}

Servientrega/Controllers/AvionController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Servientrega.Data.Models;
using Servientrega.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;

namespace Servientrega.Controllers
{
    public class AvionController : Controller
    {
        private readonly ILogger<AvionController> _logger;
        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;
        private readonly string _uri;

        public AvionController(ILogger<AvionController> logger,
                              IConfiguration configuration,
                              IMapper mapper)
        {
            _logger = logger;
            _configuration = configuration;
            _mapper = mapper;
            _uri = _configuration.GetValue<string>("UrlApi");
        }

        public async Task<IActionResult> IndexAsync()
        {
            AvionViewModel model = new();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    using var respuesta = await httpClient.GetAsync(_uri);
                    if (respuesta.StatusCode.Equals(HttpStatusCode.OK))
                    {
                        var response = await respuesta.Content.ReadAsStringAsync();
                        await httpClient.GetStringAsync(_uri);
                        var listAvion = JsonSerializer.Deserialize<List<Avion>>(response,
                            new JsonSerializerOptions() { PropertyNameCaseInsensitive = true });
                        model.ListAvion = listAvion;
                    }
                }
            }
            catch (WebException ex)
            {
                // Handle error
            }
            return View(model);
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(AvionViewModel model)
        {
            try
            {
                var jsonSerializerOptions = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };
                using (var httpClient = new HttpClient())
                {
                    var respuesta = await httpClient.PostAsJsonAsync(_uri, _mapper.Map<Avion>(model));

                    if (respuesta.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var cuerpo = await respuesta.Content.ReadAsStringAsync();
                        var erroresDelAPI = Util.Util.ExtraerErroresDelWebAPI(cuerpo);
                        List<string> ListError = new();
                        foreach (var campoErrores in erroresDelAPI)
                        {
                            string bodyError = string.Empty;
                            bodyError += $"-{campoErrores.Key}";
                            foreach (var error in campoErrores.Value)
                                bodyError += $"-{error}";
                            ListError.Add(bodyError);
                        }
                        TempData["message"] = ListError.ToString();
                    }
                    TempData["message"] = "Se registro correctamente la Avion";

                    return RedirectToAction("Index");
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return View();
        }

        public async Task<IActionResult> Update(Guid id)
        {
            AvionViewModel model = new();
            using (var httpClient = new HttpClient())
            {
                using var respuesta = await httpClient.GetAsync(_uri);
                if (respuesta.StatusCode.Equals(HttpStatusCode.OK))
                {
                    var response = await respuesta.Content.ReadAsStringAsync();
                    await httpClient.GetStringAsync(_uri);
                    var listAvion = JsonSerializer.Deserialize<List<Avion>>(response,
                        new JsonSerializerOptions() { PropertyNameCaseInsensitive = true });
                    model = _mapper.Map<AvionViewModel>(listAvion.Where(x => x.Id.Equals(id)).FirstOrDefault());
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateAsync(AvionViewModel model)
        {
            try
            {
                var jsonSerializerOptions = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };
                using (var httpClient = new HttpClient())
                {
                    await httpClient.PutAsJsonAsync($"{_uri}/{model.Id}", _mapper.Map<Avion>(model));
                    TempData["message"] = "Se actualizo correctamente la Avion";
                    return RedirectToAction("Index");
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    await httpClient.DeleteAsync($"{_uri}/{id}");
                    TempData["message"] = "Se Elimino correctamente la Avion";
                    return RedirectToAction("Index");
                }
            }
            catch (WebException)
            {
                TempData["message"] = "Se presento algunos inconvenientes con el registro ";
            }
            return RedirectToAction("Index");
        }
    }
}

Servientrega/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Servientrega.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Servientrega.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Servientrega/Views/Avion/Create.cshtml
@model AvionViewModel
@{
    ViewData["Title"] = "Registro Avion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3> Crear Nueva Avion</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <form asp-action="Create" asp-controller="Avion" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="Modelo" class="control-label"></label>
                        <input type="text" asp-for="Modelo" class="form-control" placeholder="Modelo">
                        <span asp-validation-for="Modelo" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="Capacidad" class="control-label"></label>
                        <input type="text" asp-for="Capacidad" class="form-control" placeholder="Capacidad">
                        <span asp-validation-for="Capacidad" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="Descripcion" class="control-label"></label>
                        <input type="text" asp-for="Descripcion" class="form-control" placeholder="Descripcion">
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                </div>
                <hr>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Registrar">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    <partial name="_ValidationScriptsPartial" />
}

Servientrega/Views/Avion/Index.cshtml
@model AvionViewModel
@{
    ViewData["Title"] = "Avion";
}
<div class="container">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["message"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <div class="row">
        <div class="col-sm-6">
            <h3> Listado</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Avion">Crear nuevo registro</a>
        </div>
    </div>
    <hr>
    <div class="row justify-content-center">
        @if (Model?.ListAvion?.Count() > 0)
        {
            <table class="table table-bordered table-striped" id="Table">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.Modelo)</td>
                        <td>@Html.DisplayNameFor(m => m.Capacidad)</td>
                        <td>@Html.DisplayNameFor(m => m.Descripcion)</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ListAvion)
                    {
                        <tr>
                            <td>@item.Modelo</td>
                            <td>@item.Capacidad</td>
                            <td>@item.Descripcion</td>
                            <td>
                                <a asp-controller="Avion" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                                <a asp-controller="Avion" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No se encuentra registros </p>
        }
    </div>
</div>

Servientrega/Views/Avion/Update.cshtml
@model AvionViewModel
@{
    ViewData["Title"] = "Editar Avion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3> Editar Avion</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <form asp-action="Update" asp-controller="Avion" method="post" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="Modelo" class="control-label"></label>
                        <input type="text" asp-for="Modelo" class="form-control" placeholder="Modelo">
                        <span asp-validation-for="Modelo" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="Capacidad" class="control-label"></label>
                        <input type="text" asp-for="Capacidad" class="form-control" placeholder="Capacidad">
                        <span asp-validation-for="Capacidad" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 mb-3">
                        <label asp-for="Descripcion" class="control-label"></label>
                        <input type="text" asp-for="Descripcion" class="form-control" placeholder="Descripcion">
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                </div>
                <hr>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Editar">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    <partial name="_ValidationScriptsPartial" />
}

Servientrega/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Servientrega/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Servientrega</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Servientrega</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Avion" asp-action="Index">Avion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Servientrega - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>